// Export helpers for project plans
export interface ExportProject {
  title: string;
  description: string;
  estimatedDuration?: string;
  milestones: ExportMilestone[];
  totalTasks?: number;
}

export interface ExportMilestone {
  id: string;
  title: string;
  description: string;
  dueDate: string;
  tasks: ExportTask[];
  status?: string;
}

export interface ExportTask {
  id: string;
  title: string;
  description?: string;
  priority?: 'low' | 'medium' | 'high';
  estimatedHours?: number;
  completed?: boolean;
  assignee?: string;
}

export function exportToMarkdown(project: ExportProject): string {
  const { title, description, estimatedDuration, milestones } = project;
  
  let markdown = `# ${title}\n\n`;
  markdown += `**Description:** ${description}\n\n`;
  
  if (estimatedDuration) {
    markdown += `**Estimated Duration:** ${estimatedDuration}\n\n`;
  }
  
  markdown += `**Total Milestones:** ${milestones.length}\n`;
  markdown += `**Total Tasks:** ${milestones.reduce((sum, m) => sum + m.tasks.length, 0)}\n\n`;
  
  markdown += `## Project Milestones\n\n`;
  
  milestones.forEach((milestone, index) => {
    markdown += `### ${index + 1}. ${milestone.title}\n\n`;
    markdown += `**Due Date:** ${milestone.dueDate}\n\n`;
    markdown += `**Description:** ${milestone.description}\n\n`;
    
    if (milestone.tasks.length > 0) {
      markdown += `**Tasks:**\n\n`;
      milestone.tasks.forEach((task) => {
        const priority = task.priority ? ` (${task.priority.toUpperCase()})` : '';
        const hours = task.estimatedHours ? ` - ${task.estimatedHours}h` : '';
        const status = task.completed ? '✅' : '⬜';
        markdown += `- ${status} ${task.title}${priority}${hours}\n`;
        if (task.description) {
          markdown += `  - ${task.description}\n`;
        }
      });
      markdown += `\n`;
    }
  });
  
  markdown += `---\n\n`;
  markdown += `*Generated by Nexus Tracker - Project Management Platform*\n`;
  markdown += `*Export Date: ${new Date().toLocaleDateString()}*\n`;
  
  return markdown;
}

export function exportToJSON(project: ExportProject): string {
  const exportData = {
    ...project,
    exportDate: new Date().toISOString(),
    exportedBy: 'Nexus Tracker',
    version: '1.0'
  };
  
  return JSON.stringify(exportData, null, 2);
}

export function exportToCSV(project: ExportProject): string {
  const { title, milestones } = project;
  
  let csv = 'Project,Milestone,Milestone Description,Due Date,Task,Task Description,Priority,Estimated Hours,Status\n';
  
  milestones.forEach((milestone) => {
    if (milestone.tasks.length === 0) {
      csv += `"${title}","${milestone.title}","${milestone.description}","${milestone.dueDate}","","","","",""\n`;
    } else {
      milestone.tasks.forEach((task) => {
        const priority = task.priority || '';
        const hours = task.estimatedHours || '';
        const status = task.completed ? 'Completed' : 'Pending';
        const taskDesc = task.description || '';
        
        csv += `"${title}","${milestone.title}","${milestone.description}","${milestone.dueDate}","${task.title}","${taskDesc}","${priority}","${hours}","${status}"\n`;
      });
    }
  });
  
  return csv;
}

export function downloadFile(content: string, filename: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

export function exportProjectAsMarkdown(project: ExportProject) {
  const content = exportToMarkdown(project);
  const filename = `${project.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_plan.md`;
  downloadFile(content, filename, 'text/markdown');
}

export function exportProjectAsJSON(project: ExportProject) {
  const content = exportToJSON(project);
  const filename = `${project.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_plan.json`;
  downloadFile(content, filename, 'application/json');
}

export function exportProjectAsCSV(project: ExportProject) {
  const content = exportToCSV(project);
  const filename = `${project.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_plan.csv`;
  downloadFile(content, filename, 'text/csv');
}

// Analytics event tracking
export function trackEvent(eventName: string, properties?: Record<string, any>) {
  // Google Analytics 4 event tracking
  if (typeof window !== 'undefined' && (window as any).gtag) {
    (window as any).gtag('event', eventName, {
      ...properties,
      timestamp: new Date().toISOString()
    });
  }
  
  // Console log for debugging in development
  if (process.env.NODE_ENV === 'development') {
    console.log(`Analytics Event: ${eventName}`, properties);
  }
}

// Save plan to database (placeholder for Supabase integration)
export async function savePlanToDatabase(userId: string, plan: ExportProject) {
  try {
    const response = await fetch('/api/ai/save-plan', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        userId,
        plan,
        savedAt: new Date().toISOString()
      }),
    });

    if (!response.ok) {
      throw new Error('Failed to save plan to database');
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving plan to database:', error);
    throw error;
  }
}